[package]
name = "oauth-proxy"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "oauth-proxy"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.44"
common = { path = "../common" }
axum = "0.8.8"
aws-config = { version = "1.8.12", features = ["behavior-version-latest"] }
aws-sdk-lambda = "1.112.0"
aws-sdk-ssm = "1.101.0"                                                     # Use the latest version available
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
lambda_http = "1.0.2"
url = "2.5.7"
reqwest = { version = "0.12.28", features = ["json"] }
openssl = { version = "0.10.75", features = ["vendored"] }
