name: Test Manual Trigger

on:
  workflow_dispatch:
    inputs:
      test_option:
        description: 'Test option'
        required: false
        default: 'option1'
        type: choice
        options:
          - 'option1'
          - 'option2'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: |
          echo "Manual trigger works!"
          echo "Selected option: ${{ github.event.inputs.test_option }}"
